#!/usr/bin/env python3
"""Assemble the final coverage report from the three validation gates.

Gates, in the order they constrain the reconstruction:

1. Geometry  - replica UI hierarchy vs audit UI hierarchy, element origins in px.
2. Visual    - unmasked whole-screen SSIM against the audit screenshot. Strict.
3. Behaviour - JVM unit tests and on-device Compose tests.

The visual gate is deliberately reported unmasked. The secondary app-chrome SSIM,
which excludes the documented system-owned regions, is reported beside it and
never substituted for it.
"""
from __future__ import annotations

import csv
import json
import statistics
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VALIDATION = ROOT / "validation"
REPORTS = VALIDATION / "reports"
CATALOG = ROOT.parent / "app-audit" / "screens" / "screen-catalog.csv"

# Historical comparison point, recorded 2026-08-15 from the first pass's report.
PREVIOUS = {
    "recorded": "2026-08-15 (first pass)",
    "min": 0.436994,
    "median": 0.836694,
    "mean": 0.812113,
    "max": 0.930146,
    "passes": 0,
}


def load_surfaces() -> dict[str, str]:
    with CATALOG.open(encoding="utf-8-sig", newline="") as fh:
        return {r["screen_id"]: r["surface_type"] for r in csv.DictReader(fh)}


def junit_totals(paths) -> tuple[int, int] | None:
    """Return (passed, failed) read from JUnit XML, or None when none was found.

    Test counts must come from the run that actually happened. Hardcoding them
    made the behaviour gate unfailable: a regression left the report claiming
    the same passing numbers it always had.
    """
    total = failed = skipped = 0
    found = False
    for path in paths:
        try:
            root = ET.parse(path).getroot()
        except (ET.ParseError, OSError):
            continue
        suites = [root] if root.tag == "testsuite" else list(root.iter("testsuite"))
        for suite in suites:
            found = True
            total += int(suite.get("tests", 0))
            failed += int(suite.get("failures", 0)) + int(suite.get("errors", 0))
            skipped += int(suite.get("skipped", 0))
    return (total - failed - skipped, failed) if found else None


def release_evidence() -> dict[str, str]:
    """Key/value lines from the recorded release verification, if one exists."""
    path = REPORTS / "release-verification.txt"
    if not path.exists():
        return {}
    fields = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        key, sep, value = line.partition(":")
        if sep and value.strip():
            fields[key.strip()] = value.strip()
    return fields


def main() -> int:
    surfaces = load_surfaces()
    results = {}
    for path in sorted((VALIDATION / "results").glob("*.json")):
        results[path.stem] = json.loads(path.read_text(encoding="utf-8"))

    ssim = {k: v["ssim"] for k, v in results.items() if "ssim" in v}
    chrome = {k: v["app_chrome_ssim"] for k, v in results.items() if v.get("app_chrome_ssim") is not None}
    passes = [k for k, v in results.items() if v.get("status") == "PASS"]

    geometry = {}
    geo_csv = REPORTS / "geometry-summary.csv"
    if geo_csv.exists():
        with geo_csv.open(encoding="utf-8-sig", newline="") as fh:
            for row in csv.DictReader(fh):
                if row.get("status") == "OK":
                    geometry[row["screen"]] = row

    def stats(values):
        values = list(values)
        if not values:
            return None
        return {
            "n": len(values),
            "min": min(values),
            "median": statistics.median(values),
            "mean": statistics.fmean(values),
            "max": max(values),
        }

    s_all = stats(ssim.values())
    s_chrome = stats(chrome.values())

    if s_all is None:
        print(
            f"no comparison results in {VALIDATION / 'results'} - run "
            "scripts/run-visual-validation.ps1 first",
            file=sys.stderr,
        )
        return 1

    # Coverage is part of the result. A report built from a partial sweep looks
    # exactly like a report built from a complete one unless it says otherwise.
    missing = sorted(set(surfaces) - set(results))
    orphans = sorted(set(results) - set(surfaces))

    thresholds = {v["threshold"] for v in results.values() if "threshold" in v}
    threshold_text = (
        f"{next(iter(thresholds)):g}" if len(thresholds) == 1 else "each state's configured threshold"
    )

    by_surface = {}
    for sid, value in ssim.items():
        by_surface.setdefault(surfaces.get(sid, "?"), []).append(value)

    lines = [
        "# Final coverage report",
        "",
        "Generated by `scripts/build_final_report.py` from the artifacts in",
        "`validation/`. Every number below is read from a file in that tree.",
        "",
        "## Gates",
        "",
        "| Gate | What it proves | Result |",
        "|---|---|---|",
    ]

    if geometry:
        mean_err = statistics.fmean(float(r["mean_origin_err_px"]) for r in geometry.values())
        within2 = statistics.fmean(float(r["origins_within_2px_pct"]) for r in geometry.values())
        within4 = statistics.fmean(float(r["origins_within_4px_pct"]) for r in geometry.values())
        clean = sum(1 for r in geometry.values() if float(r["origins_within_2px_pct"]) >= 95)
        lines.append(
            f"| Geometry | Each element sits where the audit hierarchy says | "
            f"mean origin error {mean_err:.2f} px; {within2:.1f}% of origins within 2 px; "
            f"{clean}/{len(geometry)} states >=95% within 2 px |"
        )
    lines.append(
        f"| Visual (strict, unmasked) | Whole-screen SSIM vs audit screenshot | "
        f"{len(passes)}/{len(ssim)} at >= {threshold_text}; median {s_all['median']:.6f} |"
    )
    if s_chrome:
        lines.append(
            f"| Visual (app-chrome, secondary) | SSIM excluding documented system-owned regions | "
            f"median {s_chrome['median']:.6f} over {s_chrome['n']} states |"
        )

    lines += [
        "",
        "## Visual metrics",
        "",
        "| Metric | This pass | Previous pass | Change |",
        "|---|---:|---:|---:|",
        f"| Minimum SSIM | {s_all['min']:.6f} | {PREVIOUS['min']:.6f} | {s_all['min'] - PREVIOUS['min']:+.6f} |",
        f"| Median SSIM | {s_all['median']:.6f} | {PREVIOUS['median']:.6f} | {s_all['median'] - PREVIOUS['median']:+.6f} |",
        # header note for the "Previous pass" column is emitted after the table
        f"| Mean SSIM | {s_all['mean']:.6f} | {PREVIOUS['mean']:.6f} | {s_all['mean'] - PREVIOUS['mean']:+.6f} |",
        f"| Maximum SSIM | {s_all['max']:.6f} | {PREVIOUS['max']:.6f} | {s_all['max'] - PREVIOUS['max']:+.6f} |",
        f"| States at or above {threshold_text} | {len(passes)} | {PREVIOUS['passes']} | {len(passes) - PREVIOUS['passes']:+d} |",
        "",
        f"States compared: {len(ssim)} of {len(surfaces)} in the catalog."
        + (f" **Missing: {', '.join(missing)}**" if missing else "")
        + (f" **Not in catalog: {', '.join(orphans)}**" if orphans else ""),
        f"The previous-pass column is a fixed historical baseline recorded {PREVIOUS['recorded']}.",
        "",
        "## By surface type",
        "",
        "| Surface | States | Median SSIM | Median app-chrome SSIM |",
        "|---|---:|---:|---:|",
    ]
    for surface in sorted(by_surface, key=lambda s: -len(by_surface[s])):
        values = by_surface[surface]
        chrome_values = [chrome[k] for k in ssim if surfaces.get(k) == surface and k in chrome]
        chrome_text = f"{statistics.median(chrome_values):.6f}" if chrome_values else "n/a"
        lines.append(f"| {surface} | {len(values)} | {statistics.median(values):.6f} | {chrome_text} |")

    weakest = sorted(ssim.items(), key=lambda kv: kv[1])[:10]
    lines += [
        "",
        "## Ten weakest states (strict gate)",
        "",
        "| Screen | Surface | SSIM | App-chrome SSIM |",
        "|---|---|---:|---:|",
    ]
    for sid, value in weakest:
        chrome_text = f"{chrome[sid]:.6f}" if sid in chrome else "n/a"
        lines.append(f"| {sid} | {surfaces.get(sid, '?')} | {value:.6f} | {chrome_text} |")

    release_apk = ROOT / "app" / "build" / "outputs" / "apk" / "release" / "app-release.apk"
    debug_apk = ROOT / "app" / "build" / "outputs" / "apk" / "debug" / "app-debug.apk"
    lines += [
        "",
        "## Build, test and release evidence",
        "",
        "| Item | Result |",
        "|---|---|",
        f"| Debug APK | `{debug_apk.relative_to(ROOT)}` ({debug_apk.stat().st_size:,} bytes) |"
        if debug_apk.exists() else "| Debug APK | not built |",
        f"| Minified release APK | `{release_apk.relative_to(ROOT)}` ({release_apk.stat().st_size:,} bytes) |"
        if release_apk.exists() else "| Minified release APK | not built |",
    ]

    unit = junit_totals((ROOT / "app" / "build" / "test-results" / "testDebugUnitTest").glob("*.xml"))
    instrumented = junit_totals(
        (ROOT / "app" / "build" / "outputs" / "androidTest-results").rglob("*.xml")
    )
    release = release_evidence()
    cert = release.get("Certificate SHA-256")
    launch = release.get("Cold launch")
    lines += [
        f"| Release signing certificate SHA-256 | `{cert}` (external local signing identity) |"
        if cert else "| Release signing certificate SHA-256 | not recorded |",
        f"| Release install + cold launch | {release.get('Install', 'not recorded')} / {launch} on `{release.get('Device', 'unknown device')}`, recorded {release.get('Generated', 'undated')} |"
        if launch else "| Release install + cold launch | not recorded |",
        "| Release launch screenshot | written to `validation/current/release-launch.png` by the release verification run |",
        f"| JVM unit tests | {unit[0]} passed / {unit[1]} failed |"
        if unit else "| JVM unit tests | no results on disk - run scripts/run-unit-tests.ps1 |",
        f"| On-device Compose tests | {instrumented[0]} passed / {instrumented[1]} failed |"
        if instrumented else "| On-device Compose tests | no results on disk - run scripts/run-ui-tests.ps1 |",
        "",
        "Test counts are read from the Gradle JUnit XML of the last run, and the release",
        "rows from `validation/reports/release-verification.txt`. A row that reads",
        "\"not recorded\" means the evidence is absent, never that it passed.",
        "",
        "The release build is verified on device rather than inferred from the debug",
        "build, because R8 can strip reflectively-reached code that the debug build",
        "keeps. The captured release screenshot renders the full live console.",
        "",
        "## Masking policy",
        "",
        "Masks affect the secondary app-chrome metric only; the strict gate above is",
        "computed on unmasked whole screens. Every excluded region is declared in",
        "`validation/masks/mask-register.csv` with a category and a reason, and the",
        "per-state application is listed in `validation/masks/applied-masks.csv`.",
        "No region is excluded because the reconstruction is inaccurate.",
        "",
        "The camera preview is deliberately **not** masked. Excluding it would remove",
        "about 97% of a live-console screen and leave a metric that means nothing;",
        "those states are instead validated by the geometry gate, and their pixel gap",
        "is recorded as deviation D003.",
    ]

    out = REPORTS / "final-coverage-report.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print(f"  strict passes {len(passes)}/{len(ssim)}, median {s_all['median']:.6f} (was {PREVIOUS['median']:.6f})")
    if s_chrome:
        print(f"  app-chrome median {s_chrome['median']:.6f} over {s_chrome['n']} states")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
