package com.irlstreamer.reconstruction.debug

import android.content.Context
import org.json.JSONObject

/**
 * Audited scroll position for each captured settings state.
 *
 * `assets/audit-scroll-anchors.json` is generated by
 * `scripts/extract_scroll_anchors.py` directly from the immutable audit UI
 * hierarchy. It records the visible label of the first preference row inside the
 * list viewport for every settings capture. Every audited row snapped flush to
 * the viewport top (row_top = 219 px on all 72 states), so restoring the audited
 * scroll position needs only that label, not a pixel offset.
 *
 * This replaces the hand-guessed list indices the debug catalog used to carry:
 * `scripts/geometry_diff.py` measured 240-600 px of vertical error on those
 * states while their horizontal error was exactly 0 px.
 */
object AuditScrollAnchors {
    private const val ASSET = "audit-scroll-anchors.json"

    @Volatile
    private var cache: Map<String, String>? = null

    fun labelFor(context: Context, screenId: String?): String? {
        if (screenId.isNullOrBlank()) return null
        return anchors(context)[screenId]
    }

    private fun anchors(context: Context): Map<String, String> {
        cache?.let { return it }
        val loaded = runCatching {
            val json = context.assets.open(ASSET).bufferedReader().use { it.readText() }
            val root = JSONObject(json)
            buildMap {
                for (key in root.keys()) {
                    root.optJSONObject(key)?.optString("label")?.takeIf { it.isNotBlank() }?.let { put(key, it) }
                }
            }
        }.getOrDefault(emptyMap())
        cache = loaded
        return loaded
    }
}
